on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.5
      - name: Install dependencies
        run: go mod tidy
      - name: Build backend project
        run: go build ./cmd/main.go
      - name: Run tests
        run: go test ./...